name = "aws_api"
version = "0.1.1"

description = "A request builder for AWS services"
licences = ["Apache-2.0"]
repository = { type = "github", user = "ryanmiville", repo = "aws_api" }

[dependencies]
gleam_stdlib = ">= 0.34.0 and < 2.0.0"
aws4_request = ">= 1.0.0 and < 2.0.0"
gleam_http = ">= 3.6.0 and < 4.0.0"

[dev-dependencies]
gleeunit = ">= 1.0.0 and < 2.0.0"
