name = "aws_request"
version = "0.1.0"

description = "An AWS request builder for Gleam"
licences = ["Apache-2.0"]
repository = { type = "github", user = "ryanmiville", repo = "aws_request" }

[dependencies]
gleam_stdlib = ">= 0.34.0 and < 2.0.0"
aws4_request = ">= 1.0.0 and < 2.0.0"
gleam_http = ">= 3.6.0 and < 4.0.0"

[dev-dependencies]
gleeunit = ">= 1.0.0 and < 2.0.0"
